language: cpp

sudo: required
dist: trusty

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.9
            - clang++-3.9
            - g++-5
            - gcc-5
            - libboost-all-dev

compiler:
    - clang
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script: mkdir b && cd b && cmake .. && make && ./tests/str_tests && ./tests/grapheme_break ../data/GraphemeBreakTest.txt
